[tool.poetry]
name = "orbiis"
version = "0.1.0"
description = ""
authors = ["admin <admin@deepc.com>"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
